export declare type PredefinedPackageDHLExpress =
  | 'JumboDocument'
  | 'JumboParcel'
  | 'Document'
  | 'DHLFlyer'
  | 'Domestic'
  | 'ExpressDocument'
  | 'DHLExpressEnvelope'
  | 'JumboBox'
  | 'JumboJuniorDocument'
  | 'JuniorJumboBox'
  | 'JumboJuniorParcel'
  | 'OtherDHLPackaging'
  | 'Parcel'
  | 'YourPackaging';
