export declare type ServiceLevelGlobegistics =
  | 'PMEI'
  | 'PMI'
  | 'eComDomestic'
  | 'eComEurope'
  | 'eComExpress'
  | 'eComExtra'
  | 'eComIPA'
  | 'eComISAL'
  | 'eComPMEIDutyPaid'
  | 'eComPMIDutyPaid'
  | 'eComPacket'
  | 'eComPacketDDP'
  | 'eComPriority'
  | 'eComStandard'
  | 'eComTrackedDDP'
  | 'eComTrackedDDU';
