name: CI

on:
  push:
    branches: [master]
  pull_request: ~
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x, 17.x, 18.x, 19.x, 20.x, 21.x, 22.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js To Build
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: make install
      - run: make install-styleguide
      - run: make build
      - run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 make test
      - name: Use Node.js ${{ matrix.node-version }} to test importing and using
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: make test-import-and-use
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: make install
      - run: make install-styleguide
      - run: make build
      - run: make lint
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: make install
      - run: make install-styleguide
      - run: make build
      - run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 make coverage
      - name: Coveralls
        if: github.ref == 'refs/heads/master'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  docs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install Dependencies
        run: make install
      - name: Generate Docs
        run: make docs
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
