name: CI

on:
  push:
    branches: [master]
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --force # TODO: Remove the `--force` flag once we've dropped support for Node 10 and can modernize the dependency matrix
      - run: npm run build
      - run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 npm test
      - run: npm run lint
      - run: npm run check
