name: CI

on:
  push:
    branches: [master]
  pull_request: ~
  workflow_dispatch: ~

jobs:
  # build checks that the app can build and runs tests on the latest node version
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 just install build test
  # node-compatibility checks that the build version of the app can be imported
  # and used on older versions of node
  node-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x, 25.x, 26.x]
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 just install build
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 just test-node-compatibility
  # typescript checks that the our Typescript definitions can be compiled without errors
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: |
          cd types/demo
          npm install
          cd ../../
          just install typescript
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: just install build lint
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: just install build
      - run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 just coverage
      - name: Coverage
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  docs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install Dependencies
        run: just install
      - name: Generate Docs
        run: just docs
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
